config/routes.rb
Sms::Application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>HSTU Books Online Store</title>
<%= stylesheet_link_tag "application" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tag %>
</head>
<body class="<%= controller.controller_name %>">
<div id="banner">
  <%= image_tag("logo.png", :alt => "rss feed") %>
  
  <%= form_tag store_path, class: 'locale' do %>
    <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
    <%= submit_tag 'submit' %>
    <%= javascript_tag "$('.locale input').hide()" %>
  <% end %>
  <%= image_tag("title.png", :alt => "rss feed") %>
  <h3>by Mohammed Dinar</h3>
   
  
</div>

<div id="nav">
<ul>
<li><a href=".."><%= t('.home') %></a></li>
<li><a href=".."><%= t('.about') %></a></li>
<li><a href=".."><%= t('.books') %></a></li>
<li><a href=".."><%= t('.news') %></a></li>
<li><a href=".."><%= t('.contact') %></a></li>
</ul>




</div>

<div id="columns">
    <div id="side">
     <div id="cart">
       <% if @cart %>
           <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
           <%= render @cart %>
          <% end %>
       <% end %>
    </div>
    <div class="add">
    <% if session[:user_id] %>
     <h2>Admin Section</h2>
      <ul>
        <li><%= link_to 'Orders', orders_path %></li>
        <li><%= link_to 'Products', products_path %></li>
        <li><%= link_to 'Users', users_path %></li>
      </ul>
      <%= button_to 'Logout', logout_path, method: :delete %>
    <% end %>
    
   
    
  
      
    </div>
     

    </div>
    
    
    
    <div id="main">
      <%= yield %>
    </div>
</div>
<div id="footer">
 <p>Copyright © 2013 AnarySoftBD. All Rights Reserved </p>
</div>
</body>
</html>